#!/usr/bin/env python3

import argparse
import csv
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.firefox.options import Options
from selenium.webdriver.firefox.service import Service
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from webdriver_manager.firefox import GeckoDriverManager


def parse_arguments():
    parser = argparse.ArgumentParser(description="Automatise l'insert de données dans my_dumbsite.")
    parser.add_argument("-u", "--url", default="http://localhost:5000", help="URL de l'application Flask (par défaut : http://localhost:5000)")
    parser.add_argument("-p", "--csvfile", required=True, help="Chemin vers le fichier CSV contenant les informations utilisateur.")
    return parser.parse_args()


def insert_user(driver, url, name, lastname, login, desc):
    driver.get(f"{url}/add_user")
    WebDriverWait(driver, 10).until(EC.presence_of_element_located((By.ID, "name")))
    driver.find_element(By.ID, "name").send_keys(name)
    driver.find_element(By.ID, "lastname").send_keys(lastname)
    driver.find_element(By.ID, "login").send_keys(login)
    driver.find_element(By.ID, "desc").send_keys(desc)
    driver.find_element(By.TAG_NAME, "form").submit()


def read_csv(file_path):
    try:
        with open(file_path, "r", encoding="utf-8") as file:
            reader = csv.reader(file, delimiter=";")
            next(reader)
            return list(reader)
    except Exception as e:
        print(f"Erreur lors de la lecture du fichier CSV : {e}")
        exit(1)


def main():
    args = parse_arguments()
    options = Options()
    options.add_argument("--headless")
    driver = webdriver.Firefox(options=options, service=Service(GeckoDriverManager().install()))

    try:
        users = read_csv(args.csvfile)
        for user in users:
            if len(user) >= 4:
                insert_user(driver, args.url, user[0], user[1], user[2], user[3])
            else:
                print(f"Ligne CSV absente : {user}")
    finally:
        driver.quit()


if __name__ == "__main__":
    main()
